spring.application.name=Tienda

# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Tienda
spring.datasource.username=postgres
spring.datasource.password=6272

# Hibernate ? crea/actualiza las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del servidor
server.port=8080

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8082/realms/tienda-realm